"""creating all from scratch

Revision ID: 52010a2a3761
Revises: 
Create Date: 2026-01-17 20:14:30.132524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52010a2a3761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=100), nullable=False),
    sa.Column('book_author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('readers',
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('reader_name', sa.String(length=80), nullable=False),
    sa.Column('reader_email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('reader_id'),
    sa.UniqueConstraint('reader_email'),
    sa.UniqueConstraint('reader_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers')
    op.drop_table('books')
    # ### end Alembic commands ###
