"""Create book model.

Revision ID: 83158e71db39
Revises: 
Create Date: 2025-12-11 18:25:37.851190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83158e71db39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=100), nullable=False),
    sa.Column('book_author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
