"""adding the reader_id and reader_name in books. books and readers relationship created

Revision ID: ab88cd4e7748
Revises: 52010a2a3761
Create Date: 2026-01-17 20:16:07.470086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab88cd4e7748'
down_revision = '52010a2a3761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reader_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reader_name', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'readers', ['reader_id'], ['reader_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reader_name')
        batch_op.drop_column('reader_id')

    # ### end Alembic commands ###
