"""reader name unique false

Revision ID: d2776b9aa692
Revises: ab88cd4e7748
Create Date: 2026-01-17 20:39:35.197589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2776b9aa692'
down_revision = 'ab88cd4e7748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('readers_reader_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('readers_reader_name_key'), ['reader_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
